name: Run HexaCode

on: [push]

jobs:
  run-hexa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run HexaCode Interpreter
        run: python HexaCodeInterpreter.py test.Hxc
